[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "titanium"
version = "0.1.0"

[dependencies]
docopt = "^0.6"
libc = "^0.2"
number_prefix = "^0.2"
open = "^1.1"
regex = "^0.1"
rustc-serialize = "^0.3"
serde = "^0.8.16"
serde_derive = "^0.8.16"
serde_yaml = "^0.5.0"
simplelog = "^0.2"
tempfile = "^2.1"
url = "^1.2"
xdg = "^2.0"

[dependencies.gdbus]
git = "https://github.com/antoyo/gdbus-rs"
version = "0.0.1"

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"
version = "0.5.0"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"
version = "0.1.0"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.mg]
git = "https://github.com/antoyo/mg"

[dependencies.mg-settings]
git = "https://github.com/antoyo/mg-settings"
version = "^0.0.5-pre"

[dependencies.mg-settings-macros]
git = "https://github.com/antoyo/mg-settings"
version = "^0.0.1"

[dependencies.webkit2gtk]
git = "https://github.com/antoyo/webkit2gtk-rs"
version = "^0.1"

[features]
default = ["gtk/v3_16", "webkit2gtk/v2_12"]

[replace."yaml-rust:0.3.4"]
branch = "avoid-quotes"
git = "https://github.com/antoyo/yaml-rust"
