[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
categories = ["gui"]
description = "Keyboard-driven web browser"
license = "MIT"
name = "titanium"
repository = "https://github.com/antoyo/titanium"
version = "0.1.1"

[dependencies]
cairo-rs = "^0.4.0"
gdk = "^0.8.0"
gio = "^0.4.0"
glib = "^0.5.0"
gtk = "^0.4.0"
gumdrop = "0.4"
log = "^0.3"
log-panics = "^1.1.0"
mg = "^0.9.0"
mg-settings = "^0.4.0"
mg-settings-macros = "^0.4.0"
number_prefix = "^0.2"
open = "^1.1"
password-store = "^0.3.0"
percent-encoding = "^1.0.0"
relm = "^0.14.0"
relm-attributes = "^0.14.0"
relm-derive = "^0.14.0"
rusqlite = "^0.7.3"
simplelog = "^0.4"
syslog = "^3.2.0"
tempfile = "3"
url = "^1.2"
webkit2gtk = "^0.4.0"
xdg = "^2.0"
zip = "^0.2.6"

[dependencies.titanium-common]
path = "titanium-common"
version = "^0.1"

[dev-dependencies]
libxdo = "0.6"

[features]
default = [
    "cairo-rs/png",
    "gtk/v3_16",
    "log-panics/with-backtrace",
    "relm/unstable",
    "relm-attributes/unstable",
    "relm-derive/unstable",
    "webkit2gtk/v2_16",
]
