[package]
name = "titanium"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[dependencies]
dbus = "^0.4"
dbus-macros = "^0.0.6"
docopt = "^0.6"
libc = "^0.2"
#mg = "^0.0.4"
mg-settings = "^0.0.2"
rustc-serialize = "^0.3"
url = "^1.2"
xdg = "^2.0"

[features]
default = ["webkit2gtk/v2_4"]

[dependencies.gdk]
git = "https://github.com/gtk-rs/gdk"
version = "0.5.0"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.0"

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"
version = "0.1.0"

[dependencies.gtk-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.mg]
git = "https://github.com/antoyo/mg"

[dependencies.webkit2gtk]
git = "https://github.com/antoyo/webkit2gtk-rs"
version = "^0.1"
