[package]
name = "titanium"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[dependencies]
gtk = "^0.1"
mg = "^0.0.3"
mg-settings = "^0.0.2"
url = "^1.2"
xdg = "^2.0"

[dependencies.webkit2]
git = "https://github.com/antoyo/webkit2-rs"
version = "^0.1"
