[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "titanium"
version = "0.1.0"

[dependencies]
cairo-rs = "^0.1.3"
error-chain = "^0.10.0"
futures = "^0.1.14"
gdk = "^0.5.3"
glib = "^0.1.3"
gtk = "^0.1.3"
gumdrop = "^0.2.0"
gumdrop_derive = "^0.2.0"
log = "^0.3"
mg-settings = "^0.2.2"
mg-settings-macros = "^0.2.1"
number_prefix = "^0.2"
open = "^1.1"
password-store = "^0.1.1"
rusqlite = "^0.7.3"
simplelog = "^0.4"
sysinfo = "^0.3.9"
syslog = "^3.2.0"
tempfile = "^2.1"
tokio-io = "^0.1.1"
tokio-serde-bincode = "^0.1.0"
url = "^1.2"
xdg = "^2.0"

[dependencies.fg-uds]
git = "https://github.com/antoyo/fg-uds-rs"

[dependencies.futures-glib]
git = "https://github.com/antoyo/futures-glib-rs"

[dependencies.mg]
git = "https://github.com/antoyo/mg"

[dependencies.relm]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-attributes]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-derive]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.titanium-common]
path = "titanium-common"
version = "^0.1"

[dependencies.webkit2gtk]
branch = "crate"
git = "https://github.com/antoyo/webkit2gtk-rs"
version = "^0.1"

[dev-dependencies]
libxdo = "^0.4.1"
tempdir = "^0.3"

[features]
default = ["cairo-rs/png", "gtk/v3_16", "relm/use_impl_trait", "webkit2gtk/v2_12"]
