[package]
name = "titanium-web-extension"
version = "0.1.0"
authors = ["Antoni Boucher <bouanto@zoho.com>"]

[lib]
crate-type = ["dylib"]

[features]
default = ["webkit2gtk-webextension/v2_12"]

[dependencies]
log = "^0.3"
regex = "^0.1"
url = "^1.2"
xdg = "^2.0"

[dependencies.gdbus]
git = "https://github.com/antoyo/gdbus-rs"
version = "0.0.1"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.glib]
git = "https://github.com/gtk-rs/glib"
version = "0.1.0"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/sys"
version = "0.3.1"

[dependencies.webkit2gtk-webextension]
git = "https://github.com/antoyo/webkit2gtk-webextension-rs"
version = "^0.1"

[dependencies.webkit2gtk-webextension-sys]
git = "https://github.com/antoyo/webkit2gtk-webextension-sys-rs"
version = "^0.2"

[replace]
"glib-sys:0.3.1" = { git = "https://github.com/antoyo/sys" }
