[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
name = "titanium-web-extension"
version = "0.1.0"

[dependencies]
futures = "^0.1.14"
glib = "^0.1.3"
glib-sys = "^0.3.4"
lazy_static = "^0.2.8"
log = "^0.3"
regex = "^0.2.2"
serde = "^1.0.7"
simplelog = "^0.4"
syslog = "^3.2.0"
tokio-io = "^0.1.1"
tokio-serde-bincode = "^0.1.0"
url = "^1.2"
webkit2gtk-webextension = "^0.1.0"
webkit2gtk-webextension-sys = "^0.2.0"
xdg = "^2.0"

[dependencies.fg-uds]
git = "https://github.com/antoyo/fg-uds-rs"

[dependencies.futures-glib]
git = "https://github.com/antoyo/futures-glib-rs"

[dependencies.relm-derive-state]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.relm-state]
branch = "feature/futures-glib"
git = "https://github.com/antoyo/relm"

[dependencies.titanium-common]
path = "../titanium-common"

[features]
default = ["webkit2gtk-webextension/v2_16"]

[lib]
crate-type = ["dylib"]
