[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Web extension for the web titanium"
license = "MIT"
name = "titanium-web-extension"
repository = "https://github.com/antoyo/titanium"
version = "0.1.0"

[dependencies]
fg-uds = "^0.1.0"
futures = "^0.1.14"
futures-glib = "^0.1.0"
glib = "^0.1.3"
glib-sys = "^0.3.4"
lazy_static = "^0.2.8"
log = "^0.3"
regex = "^0.2.2"
relm-derive-state = "^0.10.0"
relm-state = "^0.10.0"
serde = "^1.0.7"
simplelog = "^0.4"
syslog = "^3.2.0"
tokio-io = "^0.1.1"
tokio-serde-bincode = "^0.1.0"
url = "^1.2"
webkit2gtk-webextension = "^0.1.0"
webkit2gtk-webextension-sys = "^0.2.0"
xdg = "^2.0"

[dependencies.titanium-common]
path = "../titanium-common"

[features]
default = ["webkit2gtk-webextension/v2_16"]

[lib]
crate-type = ["dylib"]
