[package]
authors = ["Antoni Boucher <bouanto@zoho.com>"]
description = "Messages to be sent between the web browser and the web extension"
license = "MIT"
name = "titanium-common"
repository = "https://github.com/antoyo/titanium"
version = "0.1.0"

[dependencies]
gio = "^0.5.0"
gio-sys = "^0.7.0"
glib = "^0.6.0"
glib-sys = "^0.7.0"
gobject-sys = "^0.7.0"
log = "^0.4.1"
relm-derive-state = "^0.15.0"
relm-state = "^0.15.0"
rmp-serialize = "^0.8.0"
rustc-serialize = "^0.3.24"

[features]
default = ["gio-sys/v2_44"]
